# Generated by Django 4.2.27 on 2026-02-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_alter_emissionsubmission_id_complianceresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionsubmission',
            name='files',
            field=models.FileField(upload_to='submissions/'),
        ),
    ]
