# Generated by Django 4.2.27 on 2026-02-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_alter_emissionsubmission_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceresult',
            name='unknown_items',
            field=models.JSONField(default=list),
        ),
    ]
