# Generated by Django 4.2.27 on 2026-02-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_complianceresult_unknown_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceresult',
            name='risk_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='complianceresult',
            name='threat_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10),
        ),
    ]
