# Generated by Django 4.2.27 on 2026-02-17 10:27

from django.db import migrations, models
import submissions.models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_complianceresult_risk_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionsubmission',
            name='files',
            field=models.FileField(upload_to=submissions.models.submission_upload_path),
        ),
    ]
